(deftheme monochrome
  "Created 2019-04-26.")

(custom-theme-set-variables
 'monochrome
 '(ansi-color-names-vector ["black" "light gray" "dark gray" "light slate gray"]))

(custom-theme-set-faces
 'monochrome
 '(cursor ((((class color) (min-colors 10)) (:background "light gray"))))
 '(fringe ((t nil)))
 '(highlight ((((class color) (min-colors 10)) (:foreground "black" :background "light gray"))))
 '(region ((((class color) (min-colors 10)) (:foreground "black" :background "light gray"))))
 '(secondary-selection ((((class color) (min-colors 10)) (:foreground: "black" :background "light slate gray"))))
 '(isearch ((((class color) (min-colors 10)) (:foreground "black" :background "light gray"))))
 '(lazy-highlight ((((class color) (min-colors 10)) (:foreground "black" :background "light gray"))))
 '(linum ((((class color) (min-colors 10)) (:foreground "dark gray" :slant italic))))
 '(trailing-whitespace ((((class color) (min-colors 10)) (:background "red"))))
 '(mode-line ((((class color) (min-colors 10)) (:box (:line-width -1 :style released-button) :background "black" :foreground "#b0b0b0"))))
 '(mode-line-inactive ((((class color) (min-colors 10)) (:box (:line-width -1 :style released-button) :background "black" :foreground "#b0b0b0"))))
 '(minibuffer-prompt ((((class color) (min-colors 10)) (:weight bold :foreground "light gray"))))
 '(escape-glyph ((((class color) (min-colors 10)) (:foreground "light gray"))))
 '(error ((((class color) (min-colors 10)) (:weight bold :slant italic :foreground "red"))))
 '(warning ((((class color) (min-colors 10)) (:foreground "yellow"))))
 '(success ((((class color) (min-colors 10)) (:foreground "green"))))
 '(font-lock-builtin-face ((((class color) (min-colors 10)) (:foreground "light gray"))))
 '(font-lock-comment-face ((((class color) (min-colors 10)) (:slant italic :foreground "dark gray"))))
 '(font-lock-constant-face ((((class color) (min-colors 10)) (:weight bold :foreground "light gray"))))
 '(font-lock-function-name-face ((((class color) (min-colors 10)) (:foreground "white"))))
 '(font-lock-keyword-face ((((class color) (min-colors 10)) (:weight bold :foreground "white"))))
 '(font-lock-string-face ((((class color) (min-colors 10)) (:foreground "light slate gray"))))
 '(font-lock-type-face ((((class color) (min-colors 10)) (:weight bold :foreground "light gray"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 10)) (:weight bold :foreground "light slate gray"))))
 '(font-lock-warning-face ((((class color) (min-colors 10)) (:foreground "yellow"))))
 '(link ((((class color) (min-colors 10)) (:underline t :foreground "light gray"))))
 '(link-visited ((((class color) (min-colors 10)) (:underline t :foreground "light gray"))))
 '(show-paren-match ((t (:background "light slate gray"))))
 '(show-paren-mismatch ((t (:background "red"))))
 '(speedbar-button-face ((((class color) (min-colors 10)) (:foreground "dark gray"))))
 '(speedbar-file-face ((((class color) (min-colors 10)) (:foreground "light gray"))))
 '(speedbar-directory-face ((((class color) (min-colors 10)) (:weight bold :foreground "white"))))
 '(speedbar-tag-face ((((class color) (min-colors 10)) (:foreground "dark gray"))))
 '(speedbar-selected-face ((((class color) (min-colors 10)) (:underline "light gray" :foreground "light gray"))))
 '(speedbar-highlight-face ((((class color) (min-colors 10)) (:weight bold :background "black" :foreground "white"))))
 '(ido-first-match ((((class color) (min-colors 10)) (:foreground "light gray"))))
 '(ido-only-match ((((class color) (min-colors 10)) (:underline "light gray" :foreground "light gray"))))
 '(ido-subdir ((((class color) (min-colors 10)) (:weight bold :foreground "white"))))
 '(org-level-1 ((t (:bold t :foreground "light gray" :height 1.5))))
 '(org-level-2 ((t (:bold t :foreground "light gray" :height 1.3))))
 '(org-level-3 ((t (:bold t :foreground "light gray" :height 1.1))))
 '(org-level-4 ((t (:bold t :foreground "light gray" :height 1.0))))
 '(org-link ((t (:foreground "light slate gray" :underline t))))
 '(org-todo ((t (:bold t :foreground "red"))))
 '(org-done ((t (:bold t :foreground "green"))))
 '(helm-header ((t (:foreground "dark gray" :background "black" :underline nil :box nil))))
 '(helm-source-header ((t (:foreground "white" :background "black" :underline nil :weight bold :box (:line-width 1 :style released-button)))))
 '(helm-selection ((t (:background "light gray" :underline t :foreground "black"))))
 '(helm-selection-line ((t (:background "black"))))
 '(helm-visible-mark ((t (:foreground "black" :background "white"))))
 '(helm-candidate-number ((t (:foreground "light gray" :background "black"))))
 '(helm-separator ((t (:foreground "white" :background "black"))))
 '(helm-buffer-not-saved ((t (:foreground "white" :background "black"))))
 '(helm-buffer-process ((t (:foreground "white" :background "black"))))
 '(helm-buffer-saved-out ((t (:foreground "light gray" :background "black"))))
 '(helm-buffer-size ((t (:foreground "light gray" :background "black"))))
 '(helm-ff-directory ((t (:foreground "white" :background "black" :weight bold))))
 '(helm-ff-file ((t (:foreground "light gray" :background "black" :weight normal))))
 '(helm-ff-executable ((t (:foreground "light gray" :background "black" :weight normal))))
 '(helm-ff-invalid-symlink ((t (:foreground "white" :background "black" :weight bold))))
 '(helm-ff-symlink ((t (:foreground "white" :background "black" :weight bold))))
 '(helm-ff-prefix ((t (:foreground "black" :background "white" :weight normal))))
 '(helm-grep-cmd-line ((t (:foreground "white" :background "black"))))
 '(helm-grep-file ((t (:foreground "light gray" :background "black"))))
 '(helm-grep-finish ((t (:foreground "light gray" :background "black"))))
 '(helm-grep-lineno ((t (:foreground "light gray" :background "black"))))
 '(helm-grep-match ((t (:foreground nil :background nil :inherit helm-match))))
 '(helm-moccur-buffer ((t (:foreground "white" :background "black"))))
 '(default ((((class color) (min-colors 10)) (:foreground "light gray" :background "black")))))

(provide-theme 'monochrome)
