#! /bin/sh

xsetroot -cursor_name left_ptr &

redshift -l 54.740253:25.279191 &

setxkbmap -layout us,ru -variant ,typewriter -option "grp:caps_toggle,terminate:ctrl_alt_b" &

compton --config ~/.config/compton/compton.conf &

sxhkd &

bspc monitor LVDS-1 -d                  1 2 3 4 5 6

bspc config border_width                0
bspc config window_gap                  12

bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config border_radius               10

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#bspc rule -a Firefox desktop='^1'
#bspc rule -a Emacs desktop='^2'
#bspc rule -a Pidgin desktop='^6'

bash ~/.config/bspwm/monitor.sh





